/**
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║  leadService.ts — Max Walters Video Lead Engine                  ║
 * ║  Zero-Placeholder Policy enforced (builder-skill Rule #8)        ║
 * ╚══════════════════════════════════════════════════════════════════╝
 */

interface LeadData {
  siteId?: string;
  leadName: string;
  leadPhone: string;
  roomType: string;
  style: string;
  intensity: string;
  customNotes: string;
  remodelImageURL: string;
}

// ── Placeholder strings that indicate an unconfigured environment ─────────────
const PLACEHOLDER_PATTERNS = ['YOUR_ZAPIER', 'YOUR_URL', 'PLACEHOLDER', 'YOUR_MAKE', 'WEBHOOK_URL_HERE'];

/**
 * Environment Guard — Zero-Placeholder Policy.
 * Throws before any network call is attempted if the webhook URL is
 * missing or contains a known placeholder string.
 */
function assertWebhookUrl(url: string): void {
  if (!url) {
    const msg = '❌ CRITICAL: Lead Webhook is a placeholder. Update .env.local and restart.';
    console.error(msg);
    throw new Error('LEAD_ENGINE_MISCONFIGURED: NEXT_PUBLIC_LEAD_WEBHOOK_URL is not set.');
  }

  const hasPlaceholder = PLACEHOLDER_PATTERNS.some(p => url.toUpperCase().includes(p));
  if (hasPlaceholder) {
    const msg = '❌ CRITICAL: Lead Webhook is a placeholder. Update .env.local and restart.';
    console.error(msg);
    throw new Error(
      `LEAD_ENGINE_MISCONFIGURED: NEXT_PUBLIC_LEAD_WEBHOOK_URL contains a placeholder value ("${url}"). ` +
      'Replace it with your real Make.com or Zapier webhook URL in .env.local and restart the dev server.'
    );
  }
}

/**
 * Sends high-intent leads to the Max Walters Video Lead Engine.
 * Configured for Next.js 16 + Make.com / Zapier Webhooks.
 *
 * @throws {Error} If the webhook URL is missing or is a placeholder.
 * @throws {Error} If the network request fails or returns a non-2xx status.
 */
export const submitLead = async (data: LeadData): Promise<void> => {
  const WEBHOOK_URL = (process.env.NEXT_PUBLIC_LEAD_WEBHOOK_URL || '') as string;

  // ── Zero-Placeholder Guard ───────────────────────────────────────────────
  assertWebhookUrl(WEBHOOK_URL);

  try {
    const response = await fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ...data,
        attribution: 'High-Intent Lead generated by Max Walters Video',
        timestamp: new Date().toISOString(),
        location: 'Camarillo / 805 Area',
        source: `${process.env.NEXT_PUBLIC_BUSINESS_NAME} — Camarillo`,
      }),
    });

    if (!response.ok) {
      throw new Error(`Lead transmission failed — HTTP ${response.status} from webhook.`);
    }

    console.log(`✅ Buzz Sent: Lead captured for ${data.leadName} at ${new Date().toISOString()}`);
  } catch (error) {
    console.error('Lead Engine Error:', error);
    throw error;
  }
};
